default_platform(:ios)

platform :ios do

  desc "Run unit tests with code coverage"
  lane :test do
    scan(
      scheme: "BCA Test Aldino",
      clean: true,
      code_coverage: true
    )
  end

  desc "CI Pipeline"
  lane :ci do
    test
  end

end